"""Configuración del bot"""

from .settings import Settings, get_settings
from .constants import (
    HORARIO_ENTRADA_INICIO,
    HORARIO_ENTRADA_FIN,
    HORARIO_SALIDA_MINIMA,
    HORA_INICIO_RECUPERACION,
    HORA_FIN_RECUPERACION,
    HORA_CIERRE_REAL,
    MARGEN_TOLERANCIA_MINUTOS,
    MAX_ADVERTENCIAS_CONSECUTIVAS,
    HORAS_SEMANALES_REQUERIDAS,
    HORA_LIMITE_TARDANZA,
    DIAS_SEMANA_PERMITIDOS,
    DIAS_HISTORIAL_MIN,
    DIAS_HISTORIAL_MAX,
    DIAS_HISTORIAL_RECUPERACION_MIN,
    DIAS_HISTORIAL_RECUPERACION_MAX,
)

__all__ = [
    "Settings",
    "get_settings",
    "HORARIO_ENTRADA_INICIO",
    "HORARIO_ENTRADA_FIN",
    "HORARIO_SALIDA_MINIMA",
    "HORA_INICIO_RECUPERACION",
    "HORA_FIN_RECUPERACION",
    "HORA_CIERRE_REAL",
    "MARGEN_TOLERANCIA_MINUTOS",
    "MAX_ADVERTENCIAS_CONSECUTIVAS",
    "HORAS_SEMANALES_REQUERIDAS",
    "HORA_LIMITE_TARDANZA",
    "DIAS_SEMANA_PERMITIDOS",
    "DIAS_HISTORIAL_MIN",
    "DIAS_HISTORIAL_MAX",
    "DIAS_HISTORIAL_RECUPERACION_MIN",
    "DIAS_HISTORIAL_RECUPERACION_MAX",
]
