services:
  # 1. Base de Datos (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - botnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 2. Bot de Discord (Python)
  bot:
    build: ./bot_asistencia_main
    container_name: discord_bot
    restart: always
    command: python bot.py
    volumes:
      - ./bot_asistencia_main:/app
      - ./bot_asistencia_main/credentials.json:/app/credentials.json
    ports:
      - "8081:10000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - TZ=America/Lima
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - botnet

networks:
  botnet:
    driver: bridge

volumes:
  pg_data:
  db_data:  # Mantener volumen MariaDB anterior hasta finalizar migración
